### ISSUE TITLE
PlexAniSync not handling 429 Rate Limits

### ISSUE THREAD

**Issue by Soitora** [RickDB/PlexAniSync#49]
I've had an issue for the past week where I've started getting rate limited, only change to my AniList has been adding this (although it occurs even before doing a sync so I don't think this is the cause)

Although, this also means the error 429 might show up during some Tautulli show completions, which it has done a few times now.

Error (cleaned):
```py
...
[2021-02-05 04:00:56] [[ANILIST] Plex episode watch count [2] was higher than the one on AniList [1] which has total of 2 episodes | updating AniList entry to currently watching] 
[2021-02-05 04:00:56] [XS-Simon] [PlexAniSync[24460]] [WARNING] [[ANILIST] Plex episode watch count [2] was higher than the one on AniList [1] which has total of 2 episodes | updating AniList entry to currently watching] 
[2021-02-05 04:00:56] [XS-Simon] [urllib3.connectionpool[24460]] [DEBUG]  [Starting new HTTPS connection (1): graphql.anilist.co:443] 
[2021-02-05 04:00:56] [XS-Simon] [urllib3.connectionpool[24460]] [DEBUG]  [https://graphql.anilist.co:443 "POST / HTTP/1.1" 429 None] 
[2021-02-05 04:00:56] Plex to AniList sync finished
[2021-02-05 04:00:56] [XS-Simon] [PlexAniSync[24460]] [INFO]  Plex to AniList sync finished
```

**Comment by reconman** [comment]
https://github.com/AniList/ApiV2-GraphQL-Docs/issues/20 seems like a solution.

**Comment by reconman** [comment]
Seems like they removed the header again. That's why I just inserted a sleep for 60 seconds once the rate limit is hit.

Can you check if it's fixed with `latest`?

**Comment by reconman** [comment]
I found out that 429 is also triggered if you send too many requests per second, so I added a 0.2 second wait after each query.

**Comment by RickDB** [comment]
Looks good with current rate limit checks and cool down, we could also look into doing bulk retrieval / updates in the future to reduce queries.

**Comment by Soitora** [comment]
Thanks, I'll monitor it for a few days and see if there's any issues still :)

**Comment by Soitora** [comment]
@reconman 

Seems 429 errors is still not completely fixed

Although I also wish to know what the f is rate limiting me since I got nothing on 🤔 

```py
    [32m2021-02-09 02:17:36[0m [ANILIST] Retrieving AniList list for user: Soitora
    --- Logging error ---
    Traceback (most recent call last):
        File "C:\Users\Simon\Code\GitHub\RickDB\PlexAniSync\anilist.py", line 67, in process_user_list
            list_items = fetch_user_list(username)
        File "C:\Users\Simon\Code\GitHub\RickDB\PlexAniSync\graphql.py", line 134, in fetch_user_list
            response = send_graphql_request(query, variables)
        File "C:\Users\Simon\Code\GitHub\RickDB\PlexAniSync\graphql.py", line 167, in send_graphql_request
            response.raise_for_status()
        File "D:\Python\Python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
            raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://graphql.anilist.co/
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
        File "D:\Python\Python39\lib\logging\__init__.py", line 1079, in emit
            msg = self.format(record)
        File "D:\Python\Python39\lib\logging\__init__.py", line 923, in format
            return fmt.format(record)
        File "D:\Python\Python39\lib\site-packages\coloredlogs\__init__.py", line 1137, in format
            return logging.Formatter.format(self, record)
        File "D:\Python\Python39\lib\logging\__init__.py", line 659, in format
            record.message = record.getMessage()
        File "D:\Python\Python39\lib\logging\__init__.py", line 363, in getMessage
            msg = msg % self.args
    TypeError: not all arguments converted during string formatting
    Call stack:
        File "C:\Users\Simon\Code\GitHub\RickDB\PlexAniSync\TautulliSyncHelper.pyw", line 111, in <module>
            start()
        File "C:\Users\Simon\Code\GitHub\RickDB\PlexAniSync\TautulliSyncHelper.pyw", line 82, in start
            anilist_series = anilist.process_user_list(anilist_username)
        File "C:\Users\Simon\Code\GitHub\RickDB\PlexAniSync\anilist.py", line 82, in process_user_list
            logger.critical(f"[ANILIST] Failed to return list for user: {username}", exception)
    Message: '[ANILIST] Failed to return list for user: Soitora'
    Arguments: (HTTPError('429 Client Error: Too Many Requests for url: https://graphql.anilist.co/'),)
    [32m2021-02-09 02:17:37[0m [31mUnable to retrieve AniList list, check your username and access token[0m
```

**Comment by reconman** [comment]
While testing code, I also randomly hit the 429 while retrieving my list.

I was able to look the response in detail and changed the code so it would sleep for the time specified in the `Retry-After` HTTP header and then retry the request.

It's part of v1.3.9, here's the commit c4b8c96d21f20d4b60ec105ff8e6543c7d2d8c7d
